# Generated by Django 5.1.3 on 2025-01-14 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_api', '0002_alter_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='product_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='product_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
