# Generated by Django 5.1.3 on 2025-01-14 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_api', '0004_alter_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
